import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from './header';
import Slide from './slide';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Duy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Slide />
      </main>
    </div>
  );
};

export default Home;
