import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/common/header';
import HomePage from './home';
import Footer from '../components/common/footer';
import TopCategory from '../components/common/top-category';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <HomePage />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
